// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    partial class NZWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db00865a-39a2-4507-9481-ba5284e5e9d8"),
                            Name = "EASY"
                        },
                        new
                        {
                            Id = new Guid("98526a56-dbbf-4b86-b9a2-dd2b526f0fc1"),
                            Name = "MIDUEM"
                        },
                        new
                        {
                            Id = new Guid("e0db330e-fabe-4fe0-bc3d-c998ef244f14"),
                            Name = "HARD"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f24a5ff2-9650-4756-a141-b0d705d89235"),
                            Code = "249",
                            Name = "KHARTOUM",
                            RegionImageId = "SOME _IMAGE _FROM _KHARTOUM.png"
                        },
                        new
                        {
                            Id = new Guid("3da2c37e-2676-4c96-8a03-282e0d784fee"),
                            Code = "550",
                            Name = "OMDURMAN",
                            RegionImageId = "SOME _IMAGE _FROM _OMDURMAN.png"
                        },
                        new
                        {
                            Id = new Guid("7cadcee0-6547-4b1d-87b3-685c21662829"),
                            Code = "240",
                            Name = "BAHRI",
                            RegionImageId = "SOME _IMAGE _FROM_BAHRI.png"
                        },
                        new
                        {
                            Id = new Guid("f8bc4a64-7538-4b60-b38b-32b5986a6ca5"),
                            Code = "241",
                            Name = "HALFA",
                            RegionImageId = "SOME _IMAGE _FROM_HALFA.png"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficaltyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficaltyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficalty", "Difficalty")
                        .WithMany()
                        .HasForeignKey("DifficaltyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficalty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
